<a href="https://colab.research.google.com/github/rishav197/Python/blob/main/Practice/pandas_practice_part1_May12.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

What is Data Science ?<br>

Data Science or data analytics is a process of analyzing large set of data points to get answers on questions related to that data set

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Pandas/nyc_weather.csv')
df

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275
2,1/3/2016,40,21,47,29.86,10,8.0,0,1,NaN,277
3,1/4/2016,25,9,44,30.05,10,9.0,0,3,NaN,345
4,1/5/2016,20,-3,41,30.57,10,5.0,0,0,NaN,333
5,1/6/2016,33,4,35,30.50,10,4.0,0,0,NaN,259
6,1/7/2016,39,11,33,30.28,10,2.0,0,3,NaN,293
7,1/8/2016,39,29,64,30.20,10,4.0,0,8,NaN,79
8,1/9/2016,44,38,77,30.16,9,8.0,T,8,Rain,76
9,1/10/2016,50,46,71,29.59,4,NaN,1.8,7,Rain,109
10,1/11/2016,33,8,37,29.92,10,NaN,0,1,NaN,289
11,1/12/2016,35,15,53,29.85,10,6.0,T,4,NaN,235
12,1/13/2016,26,4,42,29.94,10,10.0,0,0,NaN,284
13,1/14/2016,30,12,47,29.95,10,5.0,T,7,NaN,266
14,1/15/2016,43,31,62,29.82,9,5.0,T,2,NaN,101
15,1/16/2016,47,37,70,29.52,8,7.0,0.24,7,Rain,340
16,1/17/2016,36,23,66,29.78,8,6.0,0.05,6,Fog-Snow,345
17,1/18/2016,25,6,53,29.83,9,12.0,T,2,Snow,293
18,1/19/2016,22,3,42,30.03,10,11.0,0,1,NaN,293
19,1/20/2016,32,15,49,30.13,10,6.0,0,2,NaN,302
20,1/21/2016,31,11,45,30.15,10,6.0,0,1,NaN,312
21,1/22/2016,26,6,41,30.21,9,NaN,0.01,3,Snow,34
22,1/23/2016,26,21,78,29.77,1,16.0,2.31,8,Fog-Snow,42
23,1/24/2016,28,11,53,29.92,8,6.0,T,3,Snow,327
24,1/25/2016,34,18,54,30.25,10,3.0,0,2,NaN,286
25,1/26/2016,43,29,56,30.03,10,7.0,0,2,NaN,244
26,1/27/2016,41,22,45,30.03,10,7.0,T,3,Rain,311
27,1/28/2016,37,20,51,29.90,10,5.0,0,1,NaN,234
28,1/29/2016,36,21,50,29.58,10,8.0,0,4,NaN,298
29,1/30/2016,34,16,46,30.01,10,7.0,0,0,NaN,257
30,1/31/2016,46,28,52,29.90,10,5.0,0,0,NaN,241

In [ ]:
df.shape

(31, 11)

In [ ]:
df.head(2)

,EST,Temperature,DewPoint,Humidity,Sea Level PressureIn,VisibilityMiles,WindSpeedMPH,PrecipitationIn,CloudCover,Events,WindDirDegrees
0,1/1/2016,38,23,52,30.03,10,8.0,0,5,NaN,281
1,1/2/2016,36,18,46,30.02,10,7.0,0,3,NaN,275

Ques1: What was max temperature in new york in the month january?

In [ ]:
df['Temperature'].max()

50

Ques2: On which days did it rain?

In [ ]:
# df['Events'].value_counts()

In [ ]:
df[df['Events']=='Rain']['EST']

8      1/9/2016
9     1/10/2016
15    1/16/2016
26    1/27/2016
Name: EST, dtype: object

Ques3: What was average speed of wind during the month?

In [ ]:
df.dtypes

EST                      object
Temperature               int64
DewPoint                  int64
Humidity                  int64
Sea Level PressureIn    float64
VisibilityMiles           int64
WindSpeedMPH            float64
PrecipitationIn          object
CloudCover                int64
Events                   object
WindDirDegrees            int64
dtype: object

In [ ]:
df['EST'] = pd.to_datetime(df['EST'])

In [ ]:
avg_windsp = df[df['EST'].dt.month==1]['WindSpeedMPH'].mean()
print(f'avg_windsp = {avg_windsp:.2f}')

avg_windsp = 6.89

What is Dataframe ?<br>

Dataframe is a main object in Pandas. It is used to represent data with rows and columns (tablular or excel spreadsheet like data)<br>

Topics
1) Creating dataframe
2) Dealing with rows and columns
3) Operations: min, max, std, describe
4) Conditional selection
5) Set_index

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/pandas02_df_basics/weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

Create dataframe using python dictionary

In [ ]:
weather_data = {
    'day': ['1/1/2017','1/2/2017','1/3/2017','1/4/2017','1/5/2017','1/6/2017'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}

# df = pd.DataFrame(weather_data)
# df

In [ ]:
df = pd.DataFrame(weather_data)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
rows, cols = df.shape

print(rows)
print(cols)

6
4

In [ ]:
# first two rows from top will print
df.head(2)

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny

In [ ]:
df.tail(2)

        day  temperature  windspeed  event
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

Use Indexing and Slicing in Dataframe

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df[:4]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [ ]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
df['event']

0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object

In [ ]:
df.describe()

       temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

Operations on Dataframe

Conditional select the data in your dataframe

In [ ]:
df[df['temperature']>=32]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
4  1/5/2017           32          4   Rain

In [ ]:
# Record when temperature is max
df[df['temperature']==df['temperature'].max()]

        day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [ ]:
# Record when temperature is min
df[df['temperature']==df['temperature'].min()]

        day  temperature  windspeed event
3  1/4/2017           24          7  Snow

In [ ]:
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.index

RangeIndex(start=0, stop=6, step=1)

In [ ]:
df.set_index('day')

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [ ]:
df.set_index('day', inplace=True) # if you want to make changes in the dataframe then you should use 'inplace=True'
df

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow
1/4/2017           24          7   Snow
1/5/2017           32          4   Rain
1/6/2017           31          2  Sunny

In [ ]:
df.index

Index(['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'], dtype='object', name='day')

In [ ]:
df.loc['1/1/2017']

temperature      32
windspeed         6
event          Rain
Name: 1/1/2017, dtype: object

In [ ]:
df.loc[['1/1/2017', '1/2/2017', '1/3/2017']]

          temperature  windspeed  event
day
1/1/2017           32          6   Rain
1/2/2017           35          7  Sunny
1/3/2017           28          2   Snow

In [ ]:
df.reset_index(inplace=True)
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [ ]:
df.loc[0]

day            1/1/2017
temperature          32
windspeed             6
event              Rain
Name: 0, dtype: object

In [ ]:
df.loc[0:3]

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [ ]:
df.set_index('event',inplace=True) # this is kind of building a hash map using event as a key
df

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Sunny  1/2/2017           35          7
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7
Rain   1/5/2017           32          4
Sunny  1/6/2017           31          2

In [ ]:
df.loc['Rain']

            day  temperature  windspeed
event
Rain   1/1/2017           32          6
Rain   1/5/2017           32          4

In [ ]:
df.loc['Sunny']

            day  temperature  windspeed
event
Sunny  1/2/2017           35          7
Sunny  1/6/2017           31          2

In [ ]:
df.loc['Snow']

            day  temperature  windspeed
event
Snow   1/3/2017           28          2
Snow   1/4/2017           24          7

Skip rows

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/pandas04_read_write_excel_csv_file/stock_data.csv')
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
# with skipping rows

df = pd.read_csv('/content/drive/MyDrive/pandas04_read_write_excel_csv_file/stock_data.csv', skiprows=2)
df

    WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1  RIL   not available   50  1023  mukesh ambani
2  TATA            5.6   -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/pandas04_read_write_excel_csv_file/stock_data.csv', header=2) # skiprows and header are kind of same
df

    WMT           4.61  484    65           n.a.
0  MSFT             -1   85    64     bill gates
1  RIL   not available   50  1023  mukesh ambani
2  TATA            5.6   -1  n.a.     ratan tata

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/pandas04_read_write_excel_csv_file/stock_data.csv', header=None, names = ["ticker","eps","revenue","people"])
df

                ticker      eps revenue         people
tickers            eps  revenue   price         people
GOOGL            27.82       87     845     larry page
WMT               4.61      484      65           n.a.
MSFT                -1       85      64     bill gates
RIL      not available       50    1023  mukesh ambani
TATA               5.6       -1    n.a.     ratan tata

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/pandas04_read_write_excel_csv_file/stock_data.csv', header=None)
df

         0              1        2      3              4
0  tickers            eps  revenue  price         people
1    GOOGL          27.82       87    845     larry page
2      WMT           4.61      484     65           n.a.
3     MSFT             -1       85     64     bill gates
4     RIL   not available       50   1023  mukesh ambani
5     TATA            5.6       -1   n.a.     ratan tata

Null Values

In [ ]:
pd.read_csv('/content/drive/MyDrive/pandas04_read_write_excel_csv_file/stock_data.csv', na_values=['n.a.', -1, 'not available'])

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/pandas04_read_write_excel_csv_file/stock_data.csv',
            na_values={'eps': [-1, 'not available'],
                       'revenue': -1,
                       'price': 'n.a.',
                       'people': 'n.a.'})
df

  tickers    eps  revenue   price         people
0   GOOGL  27.82     87.0   845.0     larry page
1     WMT   4.61    484.0    65.0            NaN
2    MSFT    NaN     85.0    64.0     bill gates
3    RIL     NaN     50.0  1023.0  mukesh ambani
4    TATA   5.60      NaN     NaN     ratan tata

In [ ]:
df.isnull().sum()

tickers    0
eps        2
revenue    1
price      1
people     1
dtype: int64

Write to CSV

In [ ]:
df.to_csv('new.csv', index=False)

In [ ]:
df.to_csv('new2.csv', columns=['tickers', 'revenue', 'price'], index=False)

Read Excel

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/pandas04_read_write_excel_csv_file/stock_data.xlsx', 'Sheet1')
df

  tickers            eps  revenue price         people
0   GOOGL          27.82       87   845     larry page
1     WMT           4.61      484    65           n.a.
2    MSFT             -1       85    64     bill gates
3    RIL   not available       50  1023  mukesh ambani
4    TATA            5.6       -1  n.a.     ratan tata

In [ ]:
def convert_people_cell(cell):
  if cell=='n.a.':
    return 'Sam Walton'

  return cell

def convert_price_cell(cell):
  if cell=='n.a.':
    return 50

  return cell

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/pandas04_read_write_excel_csv_file/stock_data.xlsx', 'Sheet1',
                  converters={
                      'people':convert_people_cell,
                      'price':convert_price_cell
                  })
df

  tickers            eps  revenue  price         people
0   GOOGL          27.82       87    845     larry page
1     WMT           4.61      484     65     Sam Walton
2    MSFT             -1       85     64     bill gates
3    RIL   not available       50   1023  mukesh ambani
4    TATA            5.6       -1     50     ratan tata

Write to Excel

In [ ]:
df.to_excel('new.xlsx', sheet_name='stocks')

In [ ]:
df.to_excel("new.xlsx", sheet_name="stocks", index=False, startrow=2, startcol=1)

Write two dataframes to two separate sheets in excel

In [ ]:
df_stocks = pd.DataFrame({
    'tickers':['GOOGL', 'WMT', 'MSFT'],
    'price':[845, 65, 64],
    'pe':[30.37, 14.26, 30.97],
    'eps':[27.82, 4.61, 2.12]
})

df_weather =  pd.DataFrame({
    'day': ['1/1/2017','1/2/2017','1/3/2017'],
    'temperature': [32,35,28],
    'event': ['Rain', 'Sunny', 'Snow']
})

In [ ]:
with pd.ExcelWriter('stocks_weather.xlsx') as writer:
  df_stocks.to_excel(writer, sheet_name='stocks', index=False)
  df_weather.to_excel(writer, sheet_name='weather', index=False)

In [ ]:
with pd.ExcelWriter('weather_stocks.xlsx') as writer:
  df_weather.to_excel(writer, sheet_name='weather', index=False)
  df_stocks.to_excel(writer, sheet_name='stocks', index=False)

Handling Missing Data - Fillna, interpolate, dropna

In [ ]:
# parse_dates=['day'] tells Pandas to automatically convert the day column into a datetime datatype while reading the CSV file
df = pd.read_csv('/content/drive/MyDrive/pandas05_handling_missing_data/weather_data.csv', parse_dates=['day'])
df

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04          NaN        9.0   Sunny
2 2017-01-05         28.0        NaN    Snow
3 2017-01-06          NaN        7.0     NaN
4 2017-01-07         32.0        NaN    Rain
5 2017-01-08          NaN        NaN   Sunny
6 2017-01-09          NaN        NaN     NaN
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   day          9 non-null      datetime64[ns]
 1   temperature  5 non-null      float64
 2   windspeed    5 non-null      float64
 3   event        7 non-null      object
dtypes: datetime64[ns](1), float64(2), object(1)
memory usage: 420.0+ bytes

fillna

Fill all NaN/Null values with one specific value

In [ ]:
df.fillna(10)

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         10.0        9.0   Sunny
2 2017-01-05         28.0       10.0    Snow
3 2017-01-06         10.0        7.0      10
4 2017-01-07         32.0       10.0    Rain
5 2017-01-08         10.0       10.0   Sunny
6 2017-01-09         10.0       10.0      10
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

Fill na using column names and dictionary

In [ ]:
df.fillna({
    'temperature':0,
    'windspeed':0,
    'event': 'No Event'
})

         day  temperature  windspeed     event
0 2017-01-01         32.0        6.0      Rain
1 2017-01-04          0.0        9.0     Sunny
2 2017-01-05         28.0        0.0      Snow
3 2017-01-06          0.0        7.0  No Event
4 2017-01-07         32.0        0.0      Rain
5 2017-01-08          0.0        0.0     Sunny
6 2017-01-09          0.0        0.0  No Event
7 2017-01-10         34.0        8.0    Cloudy
8 2017-01-11         40.0       12.0     Sunny

Use method to determine how to fill na values

In [ ]:
# forward fill
df.fillna(method='ffill')

/tmp/ipykernel_7138/1324462630.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill')

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        7.0   Sunny
6 2017-01-09         32.0        7.0   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
# backward fill
df.fillna(method='bfill')

/tmp/ipykernel_7138/3758723886.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill')

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         28.0        9.0   Sunny
2 2017-01-05         28.0        7.0    Snow
3 2017-01-06         32.0        7.0    Rain
4 2017-01-07         32.0        8.0    Rain
5 2017-01-08         34.0        8.0   Sunny
6 2017-01-09         34.0        8.0  Cloudy
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
df.fillna(method='ffill', limit=1)

/tmp/ipykernel_7138/3640860781.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='ffill', limit=1)

         day  temperature  windspeed   event
0 2017-01-01         32.0        6.0    Rain
1 2017-01-04         32.0        9.0   Sunny
2 2017-01-05         28.0        9.0    Snow
3 2017-01-06         28.0        7.0    Snow
4 2017-01-07         32.0        7.0    Rain
5 2017-01-08         32.0        NaN   Sunny
6 2017-01-09          NaN        NaN   Sunny
7 2017-01-10         34.0        8.0  Cloudy
8 2017-01-11         40.0       12.0   Sunny

In [ ]:
df.fillna(method='bfill', axis='columns') # axis is either 'index' or 'columns'

/tmp/ipykernel_7138/1197829145.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method='bfill', axis='columns') # axis is either 'index' or 'columns'
/tmp/ipykernel_7138/1197829145.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna(method='bfill', axis='columns') # axis is either 'index' or 'columns'

                   day temperature windspeed   event
0  2017-01-01 00:00:00        32.0       6.0    Rain
1  2017-01-04 00:00:00         9.0       9.0   Sunny
2  2017-01-05 00:00:00        28.0      Snow    Snow
3  2017-01-06 00:00:00         7.0       7.0     NaN
4  2017-01-07 00:00:00        32.0      Rain    Rain
5  2017-01-08 00:00:00       Sunny     Sunny   Sunny
6  2017-01-09 00:00:00         NaT       NaT     NaT
7  2017-01-10 00:00:00        34.0       8.0  Cloudy
8  2017-01-11 00:00:00        40.0      12.0   Sunny

Interpolate

Estimate missing values using nearby known values.

In [ ]:
df = df.set_index('day')
df

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
df.interpolate(method='time')

/tmp/ipykernel_7138/4148322915.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  df.interpolate(method='time')

            temperature  windspeed   event
day
2017-01-01    32.000000       6.00    Rain
2017-01-04    29.000000       9.00   Sunny
2017-01-05    28.000000       8.00    Snow
2017-01-06    30.000000       7.00     NaN
2017-01-07    32.000000       7.25    Rain
2017-01-08    32.666667       7.50   Sunny
2017-01-09    33.333333       7.75     NaN
2017-01-10    34.000000       8.00  Cloudy
2017-01-11    40.000000      12.00   Sunny

dropna

In [ ]:
df.dropna()

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
# Removes rows where all values are missing (NaN).
df.dropna(how='all')

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

In [ ]:
# 'thresh' is Minimum number of non-NaN values required to keep a row.
df.dropna(thresh=1)

            temperature  windspeed   event
day
2017-01-01         32.0        6.0    Rain
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

Inserting Missing Dates

In [ ]:
dt = pd.date_range('01-01-2017', '01-11-2017')
idx = pd.DatetimeIndex(dt)
df.reindex(idx)

            temperature  windspeed   event
2017-01-01         32.0        6.0    Rain
2017-01-02          NaN        NaN     NaN
2017-01-03          NaN        NaN     NaN
2017-01-04          NaN        9.0   Sunny
2017-01-05         28.0        NaN    Snow
2017-01-06          NaN        7.0     NaN
2017-01-07         32.0        NaN    Rain
2017-01-08          NaN        NaN   Sunny
2017-01-09          NaN        NaN     NaN
2017-01-10         34.0        8.0  Cloudy
2017-01-11         40.0       12.0   Sunny

Replacing Single value

In [ ]:
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/pandas06_handling_missing_data/weather_data.csv')
df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

In [ ]:
df.replace(-99999, np.nan)

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0      0
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0      0

Replacing List with Single Value

In [ ]:
new_df = df.replace([-99999, '0'], np.nan)
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

In [ ]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
new_df = df.replace({
    'temperature': -99999,
    'windspeed': -99999,
    'event': '0'
}, np.nan)

new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0    NaN
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0    NaN

Replacing by using Mapping

In [ ]:
new_df = df.replace({
    -99999: np.nan,
    '0': 'Sunny'
})
new_df

        day  temperature  windspeed  event
0  1/1/2017         32.0        6.0   Rain
1  1/2/2017          NaN        7.0  Sunny
2  1/3/2017         28.0        NaN   Snow
3  1/4/2017          NaN        7.0  Sunny
4  1/5/2017         32.0        NaN   Rain
5  1/6/2017         31.0        2.0  Sunny
6  1/6/2017         34.0        5.0  Sunny

Replacing using RegEx

In [ ]:
df_regex = pd.read_excel('/content/drive/MyDrive/pandas06_handling_missing_data/weather_data_regex.xlsx')
df_regex

         day temperature windspeed  event
0 2017-01-01        32 F     6 mph   Rain
1 2017-02-01      -99999     7 mph  Sunny
2 2017-03-01          28    -99999   Snow
3 2017-04-01      -99999         7      0
4 2017-05-01        32 C    -99999   Rain
5 2017-06-01          31         2  Sunny
6 2017-06-01          34         5      0

In [ ]:
df_regex.iloc[0][1]

'32 F'

In [ ]:
print(df_regex.iloc[0, 2])
print(df_regex.iloc[0, 3])

6 mph
Rain

In [ ]:
df_regex.iloc[:2, :3]

         day temperature windspeed
0 2017-01-01        32 F     6 mph
1 2017-02-01      -99999     7 mph

In [ ]:
df_regex.loc[:4, 'temperature']

0      32 F
1    -99999
2        28
3    -99999
4      32 C
Name: temperature, dtype: object

In [ ]:
df_regex.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [ ]:
df_regex.loc[:4, ['day', 'event']]

         day  event
0 2017-01-01   Rain
1 2017-02-01  Sunny
2 2017-03-01   Snow
3 2017-04-01      0
4 2017-05-01   Rain

In [ ]:
# when windspeed is 6 mph, 7 mph etc. & temperature is 32 F, 28 F etc.
new_df = df.replace({'temperature': '[A-Za-z]', 'windspeed': '[a-z]'}, '', regex=True)
new_df

        day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017       -99999          7  Sunny
2  1/3/2017           28     -99999   Snow
3  1/4/2017       -99999          7      0
4  1/5/2017           32     -99999   Rain
5  1/6/2017           31          2  Sunny
6  1/6/2017           34          5      0

Replacing list with another list

In [ ]:
df = pd.DataFrame({
    'score': ['exceptional','average', 'good', 'poor', 'average', 'exceptional'],
    'student': ['rob', 'maya', 'parthiv', 'tom', 'julian', 'erica']
})
df

         score  student
0  exceptional      rob
1      average     maya
2         good  parthiv
3         poor      tom
4      average   julian
5  exceptional    erica

In [ ]:
df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])

/tmp/ipykernel_7138/4027045839.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['poor', 'average', 'good', 'exceptional'], [1,2,3,4])

   score  student
0      4      rob
1      2     maya
2      3  parthiv
3      1      tom
4      2   julian
5      4    erica